{% set version = "0.7-5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-gmp
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gmp_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gmp/gmp_{{ version }}.tar.gz
  sha256: f5cdaf9afb4cd921924f16682a6d6097ff372c95b697f363704c367f9b13ce78

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - gmp >=5.0.1,<7
  run:
    - r-base
    - gmp >=5.0.1,<7

test:
  commands:
    - $R -e "library('gmp')"           # [not win]
    - "\"%R%\" -e \"library('gmp')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=gmp
  license: GPL-2.0-or-later
  summary: Multiple Precision Arithmetic (big integers and rationals, prime number tests, matrix computation), "arithmetic without limitations" using the C library GMP (GNU Multiple Precision Arithmetic).
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
