travis:
  secure:
    BINSTAR_TOKEN: DWWmvpHPJQvKYr/AF+j1TNmi2sBOUJaMIFRUX9cnthJS9XM3Y4TpFds+1UwvPW8e3qW3mQrvZ74ula2m+RLhrQf1kgsyrThK8GQN5ENb730DH9te6IfV/OOE9xqjZfQQjNWe8RQxzTE+URNcQ95GBqCkY6oxymTVb41XhlH8388lhKMl+yn7EPtyrhZVgYTt4G+fCFIH8aaXPl9BFj7hGTiyFqp3sbhHfpSLhNc3ca4w+zqiZ4ZnP2Wc6u4Hfaa/nErR4QFdN0W71CjlB3prAyuT30hKBo0ocPnqZCVb5QtAhBorS2uMxPdkVrexS4VxwRECwr7tKUWHpZD09XE2iH+M8tqqQQd19g8CVomJzPgoqOxKUw++PxLkC7bBvdojjFWmrTn7SYSJmsXfErnOkOXuC1dPzGtKeTyDVp9Z414AmNES5lmXzttRI3Ltk+f6Az2rqKiW7HaFMFFaTW1ryRKD5CbnwCs2IdduxbcnVcrHTFOJj8SpNakQGr6HlW8gbYwuCJluCaduTbWgpCs7q6ce3HgmDgGztf68WPxuzsRRnDr4JflvTtYMMXL+Mq1g+oSg55DA/9CyvsQ6KA4JXejDejiF/9f1VzyaGhfrfCq3yzhwmTOhbRKNNDZ7IzIX8bVw/OjQWTKqClSwwKi3wCe9TcjvTwBvq4Ipm0bfHwI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
