travis:
  secure:
    BINSTAR_TOKEN: RcT+3h8HgSLEhpyfVupN5taK3QPlNkND/UT77JT4MkCzn4fKH9b8afhA6Mmy0rfVfZ9eQdND6u24ZG16jz16B4QSN0l93GPQ7UTRc/aFzyWxGqxX2gZ7FBJBHA7Z7CwPaM4TZYyKXrr9hS6h+97zyXiTZYELfrj1FOceIN/SlaaESNUrjdP0HqwxvZRS0+b1OXyDihnEoRPOtpUlKeRXqjfSs6DrityEfLRuJsZ0MJzP1lkg27QKito10D3V8v6w13RwhK+4EMLoBIJRQ5sK3buMIe1+SSDjBL7s7+HqzKMtFGxPtSTiBF9dQ31GVTLNq8BPMQvzlXA2cA/lRL14OGxM3IYGpPLoIojOJT4U+0k+4FP2a20XxLhb2rRf1K1QdpqoQORMVVFzr/lYyIxUObHhIej/zk6DlR1ZOR9UsPlQVuKR/UiOkVWeyVpJuYba6xvfzwGe7wn4MW8wbwtB9k5ZViqUHBAwhLMwcNinA9mQg3XE7cXpiJJcJy1XJEcu24hQZ+5SvMaeO/fGVxfrWdSTijBY7sMwBsMlGq6MlLB4SDY/hH/GildYSzJllfN4KwNUHWIBCmjQwcqqUJv35691KHwhlMQFbGGgAJy5ZAtIQ5Z9l8rTHFi677TWStaWD/wPLsnbKxGz99kCUpDCEHt/1+mKglZNbHZQYadXNgg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
