appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: NlZ5iHA+tbguHxHx3bRdZFaIyFdanc5ez0KouA4HSqCcmaYgYNockjBpPWP9U5OxSMq7a9pggwarY2Cnpng3UZA+XT45yR6/Yoc0jo0jvVRn3afZRUnm6if+Sa4XdxXK/A1sUd127a3XxieycEJEmTcDFS86c8iCPCD0UCmzM7EbMYx1+qD/Y66ELFJJDFiquGT7ZSkuy65Q0l/dbAa3tRejcm2LZfk9/Ge+pYYhO2qO3TOL436QEQpx5PvPqpVIb90DWSOmldmTTZCEKDwe2gcYQQLZAF1BjjwAkje4oXx7nDhnTkpdLjIeUnCKdCD9hXMPH5BgjpU3wJvAbL/PL0zRAZGBI8G90xipBAh8vbqtPiTcajMALRtYSAfOWHECkhpIc8vR9p9zrB1xBSf5nHhGWSby/m1kX0xXgfyUHuU6s2oSCvPG4EJrh2Dnu9P5Lid1hamUbUdlWxwLVDoFaL+8gpfIFprgrdhlozDNGH9FqHBNvyaKXRY7jZ1lYOKJ82OrdxZ8nr2/GMQoIbi7R+iz97eYMYWZioyPAMdduf1pgxCd8bWzRcfMmiT0kbCcefjBJrOX2LqaamqiXLF7Fs0MRAtoJAeSOVGb738tmW+3rAtKUSc//IvMNyFWNmzAhqh8Q7NWvThL6DAiFnOXfEvZXSpf2icA9OfueKek5JA=
