travis:
  secure:
    BINSTAR_TOKEN: nVWEKSpZrbvARgAMBp2DWLsnp8sEZNi7mNAzMUyCBJFTmJqfrSPl2sj4l/yGYe5m+3evXSuNUdcI4/7YI3muHpU60XWF+ZuVjaoOs3Mrh3mfII5SwwVlB04HSATg/k0ktRI9lG5UKxvQ4GW963UPirOUGr6ATJyecuOr+30/bPDnYVa8yJwaueJtYjckjN4Ff7rltZ6sjw7F5S1pgWoAjcch9GGClhbDSSUO8md89xO9wUr+xa1hi61iPX7T6n6n2QGO4razCwapcoQdUox5QaLpn4dZ/iIkKLoJZ6DvUIsLr/Xa4kZ3Xrdgd6uaDuFgLAmBe1ZnRfGTkbbOWs/rtoaaLh0ojvnvDGECI+ZyhB5x41U0Vt5stbFbLtBnra/5tWwjb9IUly8lkh1yvHrr9UgfIcnkb7nEm6kPfab/CS+X8uOwb6B2KytxUdtx17N0sFIfLlMEoJnjhUJ9QhPHG0CMjO642EmxfljsDiQnlg+1K8s8ZiIfG/hFo6wVdbjX+l10lP4U4KTsGDILY5Fy7mAacEOhS4HAcDzcEyi0OKQY+VPguzvsCcBw7SxgaX2lyNn5OBblnn/NtxFr6otw3Cx6AgcTHIiky3x1djSsjYWh5kAzl2rHzm5RV65dnw7ucHVVyMHFgAi1B2JAyXv+nBNd+eWBrAaaiepwFFmoQNw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
