travis:
  secure:
    BINSTAR_TOKEN: aGD18zoDCIlvIv+b9qlqQUyDRPT5D/PibxxWGLUyVUrpZN58eSUYzBJN7Id/RLLIJAY+/hslZXTgEdrlg4Jmh3H+hFedVsU+ohtaouZ/zmlXmMlYyRdWKyT+9N1Y1cnpBbW+t/6zxSrUJkeZoPG4pQ9qbGXsv3yLtWwii7p+jMVZbC2OWzU+MtqL7+5bJvEFJutxjt7EBjFn4e9KbUv2Lpei/fX1w+mxXbUbuLCwnN4zg43vphxQSXaN/XlBm1j1OhlpmMRXPEMp1tU7p1mPX42Yyl/1m2viEV1PMUB7SG7JKN6Y1UDXY8rU8H3kHhu3T8q7cASvasHkcc8GLVcBmdMpIC2sT48w7emRgsG2BOgw8E7xGwrNKTYCeBPQtGH8zOjMs45Ghwy9R009+Ug4wbzA6kugz9vB3W1XzofYBEdW+GYHjEwtIZRmKJGo6vC/FMTQmgTx9jMQLMKLI9rDJhBu9JtRt/Y4dcYzrcELdiYsuMkAxqBWyAxSwUgX2HeRVPTQgr73cFApQRlHyIF7G1YnlcSQQ0Azeja55SUHuQZq/Z3Ywl2+BjqQdr4XII3nd+rVn8l8mZJgEm+5rdyzQ1imWqbtD3Cw8RYkMncD67w9/QUXERWnan19v4/wQA6fnz27x+Ejqh6MyU9ozRWCR6jBwC9I41Fkau//+sqeioQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
